### ISSUE TITLE
How do I know the port and ip address for the server

### ISSUE THREAD

**Issue by BellVirtual** [MysteryCoder456/UrsinaFPS#1]
Sorry I know this is a stupid question but if I wanted this server to work how do I go about figuring out what port its running out of.

**Comment by MysteryCoder456** [comment]
By default it runs on port 8000. You can change the port in the server script as well if you want to use another one by changing the PORT variable.

**Comment by BellVirtual** [comment]
Thanks for making a multiplayer server for ursina! your making my life a lot easier.

**Comment by BellVirtual** [comment]
I ran the server successfully from my computer could connect connect with it locally, but when I tried running the server from my computer and having my friend across the street connect through their network to the server, it timed out. My freind was using the same port and ip address as when I was connecting locally. Even when I increased the  socket timeout time it still refused to connect.
Do you know what the problem might be?

**Comment by MysteryCoder456** [comment]
To have people from outside your local network connect to your server you
need to enable Port Forwarding on your router. The process varies a lot
depending on your router manufacturer. Here's a link that may have a
tutorial on your router: https://portforward.com/. Then you have to give
your friend your public ip address and they should be able to connect to
your server.

**Comment by BellVirtual** [comment]
Ok, thank you for telling me this.
