### ISSUE TITLE
how do i start the game

### ISSUE THREAD

**Issue by AbdyZ** [MysteryCoder456/UrsinaFPS#3]
sorry if this is a dumb question but could u walk me through how to start the game

**Comment by barthogenes** [comment]
Hi, I am not the author but I got it running using these steps:
1. Start by installing python: https://www.youtube.com/watch?v=xXEt9dyvq3U
2. Then you download the code from this repository to your pc (click `Code` and then `Download ZIP`).
3. Extract the ZIP file somewhere on your pc and then open the extracted folder.
4. Hold shift and right click anywhere in the folder and click `Open PowerShell window here`.
5. Then type `pip install -r requirements.txt` and press enter.
6. Then first type `python3 server/main.py` and press enter to start the server.
7. Then perform step 4 again for a new PowerShell window, type `python3 game/main.py` into it and press enter.
8. It will then ask for a username, just type something and press enter.
9. Then it will ask for the server IP, type in `localhost` and press enter.
10. Enter `8000` for the port and press enter.
11. Now the game should start :)

**Comment by TutlaMC** [comment]
Check the README.md file. There are instructions

Link: https://github.com/MysteryCoder456/UrsinaFPS/blob/main/README.md

1. Running the server:
The server does not have any dependencies. To run it, simply run the server/main.py file.

2. Playing the game:
Install the dependencies with pip install -r requirements.txt and do python3 game/main.py to run the game.
