### ISSUE TITLE
Error running the game 

### ISSUE THREAD

**Issue by MiChaelinzo** [MysteryCoder456/UrsinaFPS#6]
<img width="460" alt="Screenshot 2023-04-05 132627" src="https://user-images.githubusercontent.com/68110223/230054725-4e817b3f-f155-4419-aa78-0b48baf684da.png">
<img width="780" alt="Screenshot 2023-04-05 132643" src="https://user-images.githubusercontent.com/68110223/230054739-de92d8c4-b897-457c-b370-afb9bb02e8be.png">

**Comment by MysteryCoder456** [comment]
The server runs on port 8000 by default. Have you changed the port in the server script to 8080?

**Comment by MiChaelinzo** [comment]
> The server runs on port 8000 by default. Have you changed the port in the server script to 8080?

Alright, thanks able to run it now!
